# Proxy Scraper and Checker Configuration

scraper:
  timeout: 10s
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  concurrent: 10

checker:
  concurrent: 200
  check_urls:
    - "http://checkip.amazonaws.com"
    - "http://google.com"
